version: "3.9"

services:
  db_pythonweb_hw_6:
    image: postgres:latest
    container_name: db_pythonweb_hw_6
    restart: "no"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./database:/var/lib/postgresql/data
